name: deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # trigger the tests here
  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: [test]
    name: deploy CDK stacks to prod
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::871600132779:role/DevopsStack-DeploymentRoleC7BBCF2C-2U2BLZBBIYPB
          aws-region: us-east-1

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Node Packages
        run: npm i
        working-directory: ./frontend

      - name: Build Astro Site
        run: npm run build
        working-directory: ./frontend

      - name: Install SSR modules
        - run: | 
          mv ssrPackage.json ./dist/server/package.json
          cd ./dist/server
          npm i 
        working-directory: ./frontend

      - name: Install Node Packages
        run: npm i
        working-directory: ./backend

      - name: CDK Synth
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "synth"
          cdk_stack: "*"
          cdk_args: "--require-approval never --verbose"
          actions_comment: false
          debug_log: true
          working_dir: "backend"
        env:
          STACK_BUILD_TARGET_ACCOUNT: prod

      - name: CDK Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "*"
          cdk_args: "--require-approval never --verbose"
          actions_comment: false
          debug_log: true
          working_dir: "backend"
        env:
          STACK_BUILD_TARGET_ACCOUNT: prod
